### PR TITLE
First round of documentation panel changes, more upcoming

### PR DESCRIPTION
**Pull request by bklam**

### CODE REVIEW

**Comment by melfree** [comment]
Can I make a suggestion? Adding a fictional resource to RESOURCE_LIST affects several features, which causes travis ci to fail, but would also show filters/columns for the fictional resource in the user key show page, and would allow columns and filters to be created in the user key form and filter form for that fictional resource. You'd also need to test these changes to keep our unit test coverage at 100%.

Instead of changing models, could you edit APIController to return the correct json message if the endpoint is demo_endpoint?

**Comment by bklam** [comment]
Yes definitely, I can do that. I was initially thinking that but I thought it might make more sense to change the models. Looking back on your suggestion though, I would agree 100% that changing the models is not the best way of handling this. Keep posted for an update after I finish office hours

**Comment by melfree** [comment]
Might want be more accurate to say that permissions are set by Student Activities, not by Student Life Office

**Comment by bklam** [comment]
Updated!

**Comment by melfree** [comment]
My only suggestion is to change the hardcoded "https://stugov.andrew.cmu.edu/staging/bridgeapi/api/v1/" under Making A Request to the Shiny Metal API to root_url

**Comment by bklam** [comment]
nice catch

**Pull request merged**
